### ISSUE TITLE
"Abbr." button

### ISSUE THREAD

**Issue by ThomasWaldmann** [rixx/abbr#3]
I see there is some templation to abbreviate everything, just for the LOLs.

But german speakers might find "Abbr." as button text confusing as it also is often used for "Abbrechen" ("Cancel").

**Comment by rixx** [comment]
This is not specifically aimed at German speakers. I might make the button text customizable in the future.

**Comment by ThomasWaldmann** [comment]
https://en.wikipedia.org/wiki/Mitsubishi_Pajero they also did not aim Pajero at Spanish speakers. :)

Configurability is overkill imho, just use "shorten" or "create shortlink" or whatever.

And, again, why close ticket when it is not done yet?

**Comment by rixx** [comment]
This ticket is closed because it is done. I might add more customizability to the project as a whole later on, but the project will not be renamed. If the button naming bothers you that much, you are of course free to maintain a fork - [abk](https://pypi.python.org/pypi/abk) is still available on PyPI.

**Comment by ThomasWaldmann** [comment]
I was not talking about project renaming. But it seems feedback is unwelcome and not managed correctly, bye.
